### ISSUE TITLE
bug: Omastar & Victreebell is missing in gen 1 

### ISSUE THREAD

**Issue by NickVandenberghe** [jakobhoeg/vscode-pokemon#9]
Sprite for omastar is missing 

I imported all 151 pokemon, but noticed omastar returns a missing sprite img
![image](https://github.com/user-attachments/assets/8daf41d2-eb8a-4109-bede-8cf05baee0d9)

**Comment by NickVandenberghe** [comment]
Victreebell is missing. There is a folder for the sprite, but it errors for victreebell

**Comment by jakobhoeg** [comment]
Thank you for noticing! I'll release a fix asap.

**Comment by NickVandenberghe** [comment]
Also if possible, would it be possible to have a better error logging ? 
I got an error that the "generation" value was invalid, however every value was just "gen1".
It was the type key that was invalid btw 

I can provide the full pokemon list json if you want to test ?

**Comment by jakobhoeg** [comment]
Yes, if you can attach it, I'll see what I can do

**Comment by NickVandenberghe** [comment]
[pokemon-list.json](https://github.com/user-attachments/files/18081365/pokemon-list.json)
Here you go :) 
Thank you for creating this extension!

**Comment by jakobhoeg** [comment]
Updated to v1.0.2

I have yet to add better error logs, but I'll aim to do that on the next major relase. Thanks again!
